version: '3'
services:
  fpm:
    build: .
    ports:
      - "800:80"
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - redis
    restart: always
    command: ["sh", '-c', 'nginx && php-fpm']

  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "33066:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret

  redis:
    image: "redis:alpine"
    ports:
      - "63799:6379"
    restart: always

volumes:
  db_data: