version: '3'
services:
  fpm:
    build: .
    ports:
      - "888:80"
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www/html
    restart: always
    command: ["sh", '-c', 'nginx && php-fpm']
